# Generated by Django 5.1.2 on 2024-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_ownership_recipient_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
